name: "💡 Feature Request"
description: Suggest a new feature for bleh
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: explanation
    attributes:
      label: Feature explanation
      description: Brief explanation of what you want to be added
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Screenshots/examples/mockups, etc
    validations:
      required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: Checklist
      options:
        - label: I've searched existing issues and this hasn't been suggested before
          required: true
        - label: I did NOT write this issue with an LLM
          required: true
